#!/bin/bash

g++ ../resources/sha256.cpp test-dataBase.cpp -o test
./test /tmp/rainbow_table.db /tmp/test_rainbow 8 100 0
g++ ../resources/sha256.cpp ../code_file/attack.cpp -o binary
./binary /tmp/rainbow_table.db /tmp/test_rainbow_hash.test /tmp/outTest.password 8 5000 /tmp/test_rainbow_clear.test
rm binary test